sudo: false
language: python
python:
  - "2.7"
install:
  - pip install pycodestyle
script:
  # E501: line too long
  - pycodestyle . --ignore=E501
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#countervandalism"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}: %{author}) %{message} - %{build_url}"
