language: python
python:
  - "2.7"
install:
  - sudo pip install pep8
script:
  - pep8 . --ignore=E501
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#countervandalism"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}: %{author}) %{message} - %{build_url}"
